### ISSUE TITLE
Launching OPL vial uLE causes issues for both Internal HDD and SMB users.

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#16]
Launching OPL via uLE (wLE 4.43a - commit d7c7459) causes issues for both Internal HDD and SMB users.  See this report: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=5790

**Comment by sp193** [comment]
It may have been fixed with commit fb53b2c, which is part of today's LaunchELF update. Please let me know if it does help.

**Comment by Jay-Jay-OPL** [comment]
Yes, this issue was also fixed. Thanks! :)
