### ISSUE TITLE
Ability to open TXT files through file browser?

### ISSUE THREAD

**Issue by gingerbeardman** [AKuHAK/uLaunchELF#17]
It would be great if using the file browser I could open text files by pressing O 

Currently I have to open the text editor, press R1, choose open, find the file.

Specifically useful for CHEATS.TXT

**Comment by sp193** [comment]
Feature added in commit f90f9b1.

**Comment by gingerbeardman** [comment]
Awesome! Thanks

**Comment by gingerbeardman** [comment]
I'm having problems saving CHEATS.TXT opened using this new method. It says "File Save Failed"

If I go back to menu, open text editor, open file, make the same edits, it saves just fine. 

What's the difference?

**Comment by sp193** [comment]
Fixed in 59a4962.

**Comment by gingerbeardman** [comment]
Thanks.

Is it possible to return to the directory the file is in after editing from file listing? currently it returns to the main menu which is slightly inconvenient.
