### ISSUE TITLE
change the filename of the packed ELF

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#21]
I noticed that when we compile wLE, we get two ELF files:

`BOOT.ELF` (not packed)
`ULE.ELF` (packed)

The issue is that the packed version is `ULE.ELF` and that is the one we tend to share so users can place that file inside the **BOOT** folder in their MCs for FMCB and etc.  The issue is that we have to rename it to `BOOT.ELF` so it follows the standard filename that we are mostly accustom to.

So I was thinking, wouldn't it be best to reverse the two filenames, so the one that gets packed should be already renamed to `BOOT.ELF`?   This way it is easier for us to share it, without having the task of having to rename it prior to sharing it?  For convenience purposes only?

In the `Makefile` (**LINE 6**), this can be done like this:

**FIND**:
```
EE_BIN = BOOT.ELF
EE_BIN_PKD = ULE.ELF
```
**REPLACE, WITH:**
```
EE_BIN = ULE.ELF
EE_BIN_PKD = BOOT.ELF
```

Your thoughts?

**Comment by sp193** [comment]
"BOOT.ELF" sounds like something that was used by a modchip. The README file for v3.41i (one of the earliest versions of uLaunchELF, after transitioning from LaunchELF) suggests its development sometimes involved the Matrix modchip.
Back then, it was not packed. It seemed to not be never packed, until @AKuHAK changed it at "wip7".

So @AKuHAK, should we change it? Would it affect your build bot?

**Comment by AKuHAK** [comment]
Hi all, my bot build uses latest versions of all dependencies except
ps2toolchain which I should update manually. It uses simple make command.
But yes, my bot is hardcoded to boot.elf .

ср, 31 окт. 2018 г., 16:20 Liu Woon Yung <notifications@github.com>:

**Comment by sp193** [comment]
That's great. Thanks!
Related commit: 9c18290.
