### ISSUE TITLE
HDD modules loading

### ISSUE THREAD

**Issue by Badore90** [AKuHAK/uLaunchELF#23]
Hello, it is possible to disable the HDD modules loading at startup?? So that the HDD would be powered-on only if/when needed (like it was in Ulaunchelf 4.42 and previous). Maybe there's an option that escapes me?

**Comment by sp193** [comment]
It's not an option because the HDD modules are loaded to load the LAUNCHELF.CNF file.
In the future, I might change it so that it'll only check the HDD for the file, only if it is launched from there. Unfortunately, its code is messy and I have too many other things to do at the moment. And so it might not be done so soon.

But in the meantime, if you have a HDD unit, why not just use it?

**Comment by Badore90** [comment]
Understood, thank you for the answer :) 
I'll explain you thoroughly:

Yes I actually use my HDD for Ps2 games (I've hundreds, 2tb HDD). However I do many other things from usb or CD/DVD drive.

i.e. i use Ps1 games from USB (with POPS), I do a lot of testing trying to make ps1 games work, installing and deleting (it will be a mess from internal HDD, for fragmentation… Plus it's not advisable to connect/disconnect the NA continuously, you risk damaging the Ps2 input or the NA).
Plus the Ps2 won't restart if the internal HDD is spinning, therefore when a game freeze POPS I've to hard-reset the Ps2 (holding the power button for about 4 seconds). With the HDD turned off, the Ps2 Always reset normally.
For these and other reasons IMHO is more comfortable to use POPS from USB.

I know people that use Ulaunchelf as main "dash", and it's annoying in case you want to boot i.e a DVD film and the internal HDD is spinning for nothing, making noise and heat. 

It would be great to have an option like: "load the hdd module at startup: yes/no" or just depending on where Ule know his LAUNCHELF.CNF file is as you were saying.

There's no hurry, I'm just fine with Ule 4.42d, you judge if and when :D

**Comment by sp193** [comment]
It is unfortunate, but it is a challenge to fix the problems that POPS has.

For now, you can use FMCB. Is there also any reason why you are not using FMCB for this? If you use FMCB, then the HDD unit would not even be activated.

On a side note, if you used FHDB, the HDD unit will be switched off when a disc is booted (DVD Video, game disc etc). This behaviour is absent from LaunchELF, but I do not understand how you can play DVD video discs from LaunchELF...

**Comment by Badore90** [comment]
Yes , I use Ps1 games with OPL (just put the OPL.ELF into the BOOT folder and named it BOOT.ELF, so POPS can reset to OPL), but I've to go to Ule many times to copy/delete the games Patches, BIOS, CHEATS, when trying to make games work, and once the HDD is powered-on it won't turn off until the Ps2 is powered-off (and Ps2 reset doesn't work either).

I do not use FHDB, Tried it, but for my tastes/needs it's better to use FMCB. Anyway thanks for the tip!
Launchelf doesn't play DVD, but I know people that use it as main dashboard. From here you can go to films on usb (via SMS) or just to the OSDSYS to boot a DVD film, but the HDD will remain powered-on.

Well, I just wanted to make you know, i'm really fine with Ule 4.42d. 
I see Wle 4.43 integrates Ule 2tb edition, so I wouldn't need anymore to have this on MC in case I need to format a 2tb HDD (plus Ule 2tb edition doesn't support very well Gamestar NAs, while Wle 4.43 have no problem with them).
But as I said above, there's no hurry. I imagine your difficulty working with this console… All I can do is to thank you for these great programs and functionality (Ule 2tb edition was a marvel!) and try to help with some beta-testing.

P.S. sorry for grammatical mistakes, I'm not english

**Comment by sp193** [comment]
I was working on LaunchELF today and was moving the configuration-loading code for supporting the HDD unit, but it worked differently from how I knew it did. I don't know when its loading the HDD modules for you.

You can try [this](https://www.sendspace.com/file/d3ugcf). If it does not load the HDD modules, then either something I did fixed the bug or it was never actually an issue.

If it still loads the HDD modules, I need more information from you:
- Where do you load LaunchELF from, and what did you use to boot it?
- What does LaunchELF print for the LaunchElfDir variable, under MISC/Debug Info?

**Comment by Badore90** [comment]
![Uploading WP_20181020_20_12_32_Pro.jpg…]()

![Uploading WP_20181020_20_15_31_Pro.jpg…]()

**Comment by Badore90** [comment]
I see the version you linked me search for the LAUNCHELF.CNF when the ULE.ELF is. I can move my CNF file in order to make Ule loading it. Maybe if it find the cnf will not load the HDD searching for it??

I think I already tried it, but I'll check to be sure...

**Comment by Badore90** [comment]
Almost forgot, about your first question:
I usually load ULE from MC. Occasionally from usb. I load it either with the button shortcut at Ps2 startup, from OPL apps, from ps2 OSDSYS and it seems to make no difference.

**Comment by sp193** [comment]
Thank you.

So it's probably trying to locate and load network configuration. I have decided to remove any support for saving/loading to a specific folder on the HDD unit, as we have not actually standardized any folder for LaunchELF (it was using FHDB's). It was either that, or priority of checking that folder on the HDD be lowered below the memory cards. But I don't see why LaunchELF should be using FHDB's folder.

But things will still be compatible with the default FHDB bundle because LaunchELF's resources are stored in the same partition as LaunchELF, which will still allow LaunchELF to load its settings from the same partition on the HDD.

I have also attempted to consolidate the mechanisms for loading/saving settings, which sometimes caused saving/loading from the HDD to fail under specific conditions (i.e. when partition is not mounted or HDD modules are not loaded). This was a multi-headed hydra that I was reluctant to fix due to its complexity. But it had to be done sooner or later.

Please try this: https://www.sendspace.com/file/003vew
I'll made a new public release in a few days, if nothing else was ruined through all these major changes.

**Comment by Badore90** [comment]
I tried Yesterday moving the LAUNCHELF.CNF to where ULE 4.43 was. It perfectly loaded the CNF but powered-on the HDD too as always.
Then I copied Ule 4.42d to mass and delete the CNF. it failed to load any CNF obviously, but doesn't load the modules (unless I access the hdd).

One thing I noticed: I copy/paste Ule 4.42d from mc1 to mass with Ule 4.43 from your (first) link. It seemed to correctly finish the pasting process, but when I start the ELF I got a black screen.
Then I repeated the process with Ule 4.42d and the ELF start correctly.

ULE 4.42d never failed a copy/paste as far as I remember, and I copied hundred of gamesaves from 64MB MCs and programs hundreds of times.
The only little problem with ULE 4.42 is that sometimes it freeze after the pasting process. Always after (usually when I'm leaving the pasting directory), so I just have to reset the Ps2, but I don't remeber a single file being not perfectly copied.

I'll try your last link later

**Comment by Badore90** [comment]
Perfect, with this one (BOOT-181021) the HDD doesn't turn on :D

**Comment by Badore90** [comment]
Now the only thing retaining me from upgrading Ule is the copy/paste problem.
It's a new one right? If I remember correctly Ule 4.43a (and Ule 2tb edition 2) don't have this kind of issue.

**Comment by sp193** [comment]
That is great.

As for the problem with "paste failed", please do a disk check on your USB disk and try again.
I could never really replicate this and the code for copying files has not been changed for years. Plus other software also use the USB drivers, so it is difficult to see why this happens.

**Comment by Badore90** [comment]
It seems I'm not the only one experiencing this: http://www.ps2-home.com/forum/viewtopic.php?f=16&t=5848&start=10

My HDD seems perfect. I thought it could be a problem related to my old FMCB version (1.953), I know there are changes at the USB modules etc... Bit I know Jay-Jay was using the latest FMCB version when writing in that topic.

I'll do some testing, if I'll find out something I'll make you know

**Comment by sp193** [comment]
By disk check, I mean a filesystem check (right-click on the disk in My Computer, select Tools tab).
I know you aren't the first to mention this, but I cannot fix what I cannot replicate. Neither can I do a static analysis of a bug (nevermind debugging), when I cannot tell where it is.

**Comment by Badore90** [comment]
You're right, I just wasn't sure if you were aware of it :)

About the disk check, my pc says (I translate): 
"Isn't necessary to do an analisys.
No error detected in the unit. If you desire you can anyway do the analisys… etc"

I'll do the complete analysis and report to you

**Comment by Badore90** [comment]
Ok done. I check the details too, but there are no problems.

**Comment by sp193** [comment]
I see. Thank you for confirming that.

I would like to invite you to participate in this experiment, if you can have your PC connected to your PS2. It does not have to be a direct connection (as long as you can get a network connection).
You would need to have your IPCONFIG.DAT file created first.

Thread: https://github.com/ps2dev/ps2sdk/issues/70#issuecomment-432328727

**Comment by Badore90** [comment]
Oh this is a great idea, but unfortunately i don't have a pc (I'm borrowing this one only for short moments, Usually I can't use it for long…). 

I'll see what I can do

**Comment by sp193** [comment]
Do you not have a computer at all? If it is at least something that can run Java, I can make a Java program.
