### ISSUE TITLE
Weird font text shown under wLE settings (footer area).

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [AKuHAK/uLaunchELF#26]
Testing: **_wLaunchELF_v4.43a (Build-9c18290-2018-11-03)_**

There is some weird font text shown in the following places:

Navigate to:
wLE > Settings > Screen Settings > (place cursor next to the following items - don't need to run them:)

- Skin Settings
- Load Skin CNF
- Save Skin CNF

If you look in the footer, there is some weird font text shown for the button options.

_**Also...**_

wLE > Settings > Startup Settings > (place cursor next to the following items - don't need to run them:)

- Number of CNF's
- Initial Delay:
- Default Timeout

If you look in the footer, there is some weird font text shown for the button options.

**Comment by sp193** [comment]
Fixed in a513c2b. It is related to commit 10212c0.
Thanks for bringing this up.
