### ISSUE TITLE
Cant rename file/folders on a mounted VMC

### ISSUE THREAD

**Issue by carljtc** [AKuHAK/uLaunchELF#28]
The rename function doesnt do nothing when used with VMCs.

Tested with wLaunchELF v4.43a wed oct  31 16:52:25 2018 commit: 66ca9b2 and previous versions of wLaunchELF.

**Comment by sp193** [comment]
Are you able to compile LaunchELF yourself?

I think the VMC module does not rename files correctly.
[This line](https://github.com/AKuHAK/uLaunchELF/blob/master/vmc_fs/vmc_io.c#L1629):
```
writePage(gendata.fd, (unsigned char *)&dirent, (dirent_cluster * g_Vmc_Image[f->unit].header.pages_per_cluster) + gendata.dirent_page);
```

...should have probably been:
```
writePage(gendata.fd, (unsigned char *)&dirent, (dirent_cluster + gendata.first_allocatable) * g_Vmc_Image[unit].header.pages_per_cluster + gendata.dirent_page);
```

The existing line does not consider _gendata.first_allocatable_.

**Comment by carljtc** [comment]
Oh, thanks for taking a look at it :). I cant compile :|

**Comment by sp193** [comment]
I think it'll be fine.... although I cannot test this either. 9d9f8ca
If there will be more to add to this issue, please feel free to reopen it.
